const menus = [
	{
		id: '1001',
		functionCode: '1001',
		functionName: '监测预警',
		url: '/sms/operation',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: false,
		sortIndex: 1,
	},
	{
		id: '1002',
		functionCode: '1002',
		functionName: '信息推送',
		url: '/sms/infoPush',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: false,
		sortIndex: 1,
		children: [
			{
				id: '1020',
				functionCode: '1020',
				functionName: '信息发送',
				url: '/sms/infoPush',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '1002',
				hidden: false,
				sortIndex: 1,
				children: [
					{
						id: '1022',
						functionCode: '1022',
						functionName: '发送查询',
						url: '/sms/infoPush/sendSearch',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1020',
						hidden: false,
						sortIndex: 1,
						children: [],
					},
					{
						id: '1023',
						functionCode: '1023',
						functionName: '新建信息',
						url: '/sms/infoPush/newInfo',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1020',
						hidden: false,
						sortIndex: 2,
					},
				],
			},
			{
				id: '1021',
				functionCode: '1021',
				functionName: '信息设置',
				url: '/sms/infoPush/rule',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '1002',
				hidden: false,
				sortIndex: 2,
				children: [
					{
						id: '1024',
						functionCode: '1024',
						functionName: '规则设置',
						url: '/sms/infoPush/rule',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1021',
						hidden: false,
						sortIndex: 1,
					},
					{
						id: '1025',
						functionCode: '1025',
						functionName: '分组设置',
						url: '/sms/infoPush/group',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1021',
						hidden: false,
						sortIndex: 2,
					},
					{
						id: '1026',
						functionCode: '1026',
						functionName: '开关设置',
						url: '/sms/infoPush/onOff',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1021',
						hidden: false,
						sortIndex: 3,
					},
					{
						id: '1027',
						functionCode: '1027',
						functionName: '模板设置',
						url: '/sms/infoPush/template',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1021',
						hidden: false,
						sortIndex: 4,
					},
					{
						id: '1028',
						functionCode: '1028',
						functionName: '在岗设置',
						url: '/sms/infoPush/job',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 1,
						parentId: '1021',
						hidden: false,
						sortIndex: 5,
					},
					{
						id: '1056',
						functionCode: '1056',
						functionName: '总开关',
						url: '/sms/infoPush/onOff/switch',
						menuType: 1,
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 2,
						parentId: '1021',
						hidden: false,
						sortIndex: 6,
					},
					{
						id: '1057',
						functionCode: '1057',
						functionName: '熔断开关',
						url: '/sms/infoPush/onOff/fushing',
						menuType: 1,
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 2,
						parentId: '1021',
						hidden: false,
						sortIndex: 6,
					},
				],
			},
		],
	},
	{
		id: '1003',
		functionCode: '1003',
		functionName: '报警信息管理',
		url: '/sms/dataStatict',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: false,
		sortIndex: 1,
		children: [
			{
				id: '1033',
				functionCode: '1033',
				functionName: '统计导出',
				url: '/sms/dataStatict/export',
				menuType: 2,
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 2,
				parentId: '1003',
				hidden: false,
				sortIndex: 1,
			},
		],
	},
	{
		id: '1037',
		functionCode: '1037',
		functionName: '故障维修',
		url: '/sms/breakDown',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: false,
		sortIndex: 1,
	},
	{
		id: '1031',
		functionCode: '1031',
		functionName: '联锁报警',
		url: '/sms/chainAlarm',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: false,
		sortIndex: 1,
		children: [
			{
				id: '1055',
				url: '/sms/chainAlarm/config',
				functionCode: '1055',
				functionName: '联锁配置',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '1031',
				hidden: false,
				sortIndex: 1,
				children: [],
			},
			{
				id: '1056',
				url: '/sms/chainAlarm/record',
				functionCode: '1056',
				functionName: '联锁报警记录',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '1031',
				hidden: false,
				sortIndex: 2,
			},
			{
				id: '1060',
				functionCode: '1060',
				functionName: '联锁报警总开关',
				url: '/sms/chainAlarm/config/switch',
				menuType: 1,
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 2,
				parentId: '1031',
				hidden: false,
				sortIndex: 1,
			},
		],
	},
	{
		id: '2004',
		functionCode: '2004',
		functionName: '系统管理',
		url: '/systemsManage',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: false,
		sortIndex: 1,
		children: [
			{
				id: '1014',
				functionCode: '1014',
				functionName: '用户管理',
				url: '/systemsManage/users',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 7,
				children: [],
			},
			{
				id: '1015',
				functionCode: '1015',
				functionName: '角色管理',
				url: '/systemsManage/roles',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 8,
				children: [],
			},
			{
				id: '1016',
				functionCode: '1016',
				functionName: '岗位管理',
				url: '/systemsManage/position',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 9,
				children: [],
			},
			{
				id: '1020',
				functionCode: '1020',
				functionName: '区域管理',
				url: '/systemsManage/area',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 13,
				children: [],
			},
			{
				id: '1017',
				functionCode: '1017',
				functionName: '部门管理',
				url: '/systemsManage/departs',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 10,
				children: [],
			},
			{
				id: '1018',
				functionCode: '1018',
				functionName: '日志管理',
				url: '/systemsManage/logs',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 11,
				children: [],
			},
			{
				id: '1019',
				functionCode: '1019',
				functionName: '菜单管理',
				url: '/systemsManage/menus',
				menuType: 'WEB',
				icon: null,
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 12,
				children: [],
			},
			{
				id: '1030',
				functionCode: '1030',
				functionName: '阈值管理',
				url: '/systemsManage/threshold',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 6,
			},
			{
				id: '1031',
				functionCode: '1031',
				functionName: '登录日志管理',
				url: '/systemsManage/loginLogs',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 7,
			},
			{
				id: '1032',
				functionCode: '1032',
				functionName: '图标管理',
				url: '/systemsManage/layer',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 8,
			},
			{
				id: '1033',
				functionCode: '1033',
				functionName: '数据权限管理',
				url: '/systemsManage/dataAuth',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 9,
			},
			{
				id: '1034',
				functionCode: '1034',
				functionName: '设备管理',
				url: '/systemsManage/resources/equipmentLocationManagement',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 10,
				children: [
					{
						id: '1058',
						functionCode: '1058',
						functionName: '总开关',
						url: '/systemsManage/resources/equipmentLocationManagement/switch',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 2,
						parentId: '1034',
						hidden: false,
						sortIndex: 10,
					},
					{
						id: '1059',
						functionCode: '1059',
						functionName: '修改',
						url: '/systemsManage/resources/equipmentLocationManagement/edit',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 2,
						parentId: '1034',
						hidden: false,
						sortIndex: 10,
					},
					{
						id: '1060',
						functionCode: '1060',
						functionName: '删除',
						url: '/systemsManage/resources/equipmentLocationManagement/del',
						menuType: 'WEB',
						icon: '',
						isEnable: 1,
						systemSign: '',
						funType: 2,
						parentId: '1034',
						hidden: false,
						sortIndex: 10,
					},
				],
			},
			{
				id: '1039',
				functionCode: '1039',
				functionName: '报警类型管理',
				url: '/systemsManage/alarmTypeManage',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 10,
			},
			{
				id: '1040',
				functionCode: '1040',
				functionName: '审批配置管理',
				url: '/systemsManage/approveOption',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 10,
			},
			{
				id: '1041',
				functionCode: '1041',
				functionName: '大屏产能管理',
				url: '/systemsManage/capacity',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 14,
			},
			{
				id: '1042',
				functionCode: '1042',
				functionName: '图层管理',
				url: '/systemsManage/layer',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 15,
			},
			{
				id: '1043',
				functionCode: '1043',
				functionName: '设备开关管理',
				url: '/systemsManage/deviceSwitch',
				menuType: 'WEB',
				icon: '',
				isEnable: 1,
				systemSign: '',
				funType: 1,
				parentId: '2004',
				hidden: false,
				sortIndex: 16,
			},
		],
	},
	{
		id: '1035',
		functionCode: '1035',
		functionName: '消息通知',
		url: '/stationMessage',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '0',
		hidden: true,
		sortIndex: 1,
	},
	{
		id: '1036',
		functionCode: '1036',
		functionName: '消息通知',
		url: '/systemsManage/resources/deviceInstance',
		menuType: 'WEB',
		icon: '',
		isEnable: 1,
		systemSign: '',
		funType: 1,
		parentId: '2004',
		hidden: true,
		sortIndex: 11,
	},
];

export default menus;
